### ISSUE TITLE
Why does it make my game's fps lower

### ISSUE THREAD

**Issue by ScarletVirus** [IsaiahMC/thallium#16]
When I installed this mod, sodium MOD, and lithium mod, my game’s fps was lower than without this mod.And In 1.16.2 This mod makes my tps lower than vanilla. 
English is not my native language,I can't speak English well ,Most of them use GOOGLE Translate，Please excuse me

**Comment by Miros77** [comment]
turn it off
![2](https://user-images.githubusercontent.com/59547044/91204536-ea045e00-e70c-11ea-900a-8852515a8d9f.JPG)

**Comment by Miros77** [comment]
> When I installed this mod, sodium MOD, and lithium mod, my game’s fps was lower than without this mod.And In 1.16.2 This mod makes my tps lower than vanilla.
> English is not my native language,I can't speak English well ,Most of them use GOOGLE Translate，Please excuse me

turn it off
![2](https://user-images.githubusercontent.com/59547044/91204747-2fc12680-e70d-11ea-8601-f71d5c8d903f.JPG)

**Comment by JeffAxe123** [comment]
https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec
