### ISSUE TITLE
actually there was a way to get into the thallium menu (machine translation)

### ISSUE THREAD

**Issue by Miros77** [IsaiahMC/thallium#18]
![1](https://user-images.githubusercontent.com/59547044/91624536-97939d80-e9a9-11ea-9abf-7499a0478072.JPG)
press Shift+p
![2](https://user-images.githubusercontent.com/59547044/91624542-a2e6c900-e9a9-11ea-9dee-a625f9f6081e.JPG)

**Comment by by-moan** [comment]
what version of sodium do you use because it crashes to me

**Comment by Miros77** [comment]
this one (slightly altered)
[Thallium...zip](https://github.com/IsaiahPatton/thallium/files/5388485/Thallium.zip)
