### ISSUE TITLE
thallium sources on github are out of date

### ISSUE THREAD

**Issue by alxpettit** [IsaiahMC/thallium#23]
sources are for 1.7 despite latest being 1.9 :S

Is this still GPLv3 or is it closed source now?

**Comment by Jarfeh** [comment]
If you're in true need of an open source optimization mod, just go look at sodium

**Comment by alxpettit** [comment]
:(

**Comment by alxpettit** [comment]
@Jarfeh Sodium is good but doesn't support Fabric rendering API.

**Comment by Jarfeh** [comment]
You can also try the canvas render

**Comment by Heath123** [comment]
@alxpettit You should prbably switch to Sodium: https://gist.github.com/jellysquid3/26b28b532b08b951852e9b5062916bec
