### ISSUE TITLE
When I click Thallium options - Crash (machine translation) 

### ISSUE THREAD

**Issue by Miros77** [IsaiahMC/thallium#9]
When I click Thallium options

Crash

---- Minecraft Crash Report -------- Minecraft Crash Report ----// Don't do that.
Time: 16.08.20 2:33Description: Rendering screen
java.lang.NoSuchMethodError: net.minecraft.class_332.method_27534(Lnet/minecraft/class_4587;Lnet/minecraft/class_327;Lnet/minecraft/class_2561;III)V at thallium.fabric.gui.ThalliumOptionsScreen.method_25394(ThalliumOptionsScreen.java:67) at net.minecraft.class_757.method_3192(class_757.java:603) at net.minecraft.class_310.method_1523(class_310.java:1021) at net.minecraft.class_310.method_1514(class_310.java:654) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Render threadStacktrace: at thallium.fabric.gui.ThalliumOptionsScreen.method_25394(ThalliumOptionsScreen.java:67)
-- Screen render details --Details: Screen name: thallium.fabric.gui.ThalliumOptionsScreen Mouse location: Scaled: (167, 183). Absolute: (334.000000, 366.000000) Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2.000000Stacktrace: at net.minecraft.class_757.method_3192(class_757.java:603) at net.minecraft.class_310.method_1523(class_310.java:1021) at net.minecraft.class_310.method_1514(class_310.java:654) at net.minecraft.client.main.Main.main(Main.java:215) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
-- System Details --Details: Minecraft Version: 1.16.1 Minecraft Version ID: 1.16.1 Operating System: Windows 7 (amd64) version 6.1 Java Version: 1.8.0_251, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 240147048 bytes (229 MB) / 614932480 bytes (586 MB) up to 1932787712 bytes (1843 MB) CPUs: 2 JVM Flags: 5 total; -Xmn128M -Xmx1856M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC Fabric Mods:  fabric: Fabric API 0.14.1+build.372-1.16 fabric-api-base: Fabric API Base 0.1.3+12a8474c02 fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902 fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802 fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602 fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02 fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02 fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02 fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02 fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102 fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902 fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602 fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02 fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02 fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602 fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802 fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02 fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002 fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02 fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02 fabricloader: Fabric Loader 0.8.9+build.203 lithium: Lithium 0.5.0 minecraft: Minecraft 1.16.1 phosphor: Phosphor 0.6.0+build.7 sodium: Sodium 0.1.0-SNAPSHOT thallium: Thallium 1.7 Launched Version: fabric-loader-0.8.9+build.203-1.16.1 Backend library: LWJGL version 3.2.2 build 10 Backend API: GeForce GT 620M/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation GL Caps: Using framebuffer using OpenGL 3.0 Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric' Type: Client (map_client.txt) Resource Packs:  Current Language: Русский (Россия) CPU: 2x Intel(R) Pentium(R) CPU B960 @ 2.20GHz

**Comment by QPCrummer** [comment]
Same problem except I have BBOR mod, which overlaps with the thallium settings button.
